In [1]:
from pandas_datareader import data
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
start = '2019-06-01'
end = '2020-06-01'

df = data.DataReader('^N225', 'yahoo', start, end)

In [3]:
df.head(20)

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2019-06-03,20438.029297,20305.740234,20327.869141,20410.880859,67400000,20410.880859
2019-06-04,20464.570312,20289.640625,20435.859375,20408.539062,69200000,20408.539062
2019-06-05,20800.640625,20646.150391,20667.890625,20776.099609,72300000,20776.099609
2019-06-06,20842.279297,20745.839844,20745.839844,20774.039062,59600000,20774.039062
2019-06-07,20907.769531,20816.580078,20859.779297,20884.710938,50700000,20884.710938
2019-06-10,21166.119141,21077.949219,21095.400391,21134.419922,58200000,21134.419922
2019-06-11,21227.179688,21066.619141,21099.539062,21204.279297,52100000,21204.279297
2019-06-12,21259.699219,21118.750000,21130.390625,21129.720703,56500000,21129.720703
2019-06-13,21111.230469,20932.130859,21040.910156,21032.000000,65700000,21032.000000
2019-06-14,21119.730469,20971.179688,21049.410156,21116.890625,60400000,21116.890625
2019-06-17,21185.250000,21044.619141,21094.960938,21124.000000,49100000,21124.000000
2019-06-18,21153.650391,20924.189453,21111.769531,20972.710938,54600000,20972.710938
2019-06-19,21358.720703,21213.429688,21223.169922,21333.869141,64100000,21333.869141
2019-06-20,21491.390625,21377.269531,21417.740234,21462.859375,55700000,21462.859375
2019-06-21,21497.820312,21221.699219,21487.669922,21258.640625,89000000,21258.640625
2019-06-24,21317.859375,21185.669922,21223.560547,21285.990234,43200000,21285.990234
2019-06-25,21313.769531,21114.470703,21238.070312,21193.810547,53900000,21193.810547
2019-06-26,21129.640625,21035.839844,21067.679688,21086.589844,50300000,21086.589844
2019-06-27,21338.169922,21123.970703,21156.880859,21338.169922,61300000,21338.169922
2019-06-28,21324.929688,21199.849609,21282.220703,21275.919922,62100000,21275.919922